### ISSUE TITLE
`melt_pool_geometry_part` is not configuring correctly

### ISSUE THREAD

**Issue by gknapp1** [ORNL-MDF/Myna#59]
## Issue

The `myna config` step does not add the correct information to the input file and does not create the `myna_resources` or `myna_output` directories. The `myna config --output ic.yaml` command does create the "ic.yaml" file, but the added data is not present. No error message is thrown.

I suspect this is related to some change introduced by #52.

## Reproducing

Environment: Ubuntu `dev` build (December 4, 2024) of the [Myna Docker container](https://github.com/ORNL-MDF/containers).

Input file to reproduce:
```yaml
steps:
- 3dthesis:
    class: melt_pool_geometry_part
    application: thesis
    executable: 3DThesis
    configure: {res: 2.5e-05}
    execute: {np: 2, batch: true}
data:
  build:
    datatype: Peregrine
    name: myna_output
    path: ..
    parts:
      P5:
        layers: [51]
```

Command:
`myna config --output ic.yaml`
